apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
  name: mysql-pod
spec:
  containers:
  - image: mysql
    name: mysql-pod
    env:
      - name: MYSQL_DATABASE
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: MYSQL_DATABASE
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: MYSQL_ROOT_PASSWORD
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  selector:
    run: mysql-pod
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
