apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: phpadmin-pod
  name: phpadmin-pod
spec:
  containers:
  - image: phpmyadmin
    name: phpadmin-container
    env:
      - name: PMA_HOST
        valueFrom:
          configMapKeyRef:
            name: phpadmin-config
            key: PMA_HOST
      - name: PMA_PORT
        valueFrom:
          configMapKeyRef:
            name: phpadmin-config
            key: PMA_PORT
      - name: PMA_USER
        valueFrom:
          secretKeyRef:
            name: phpadmin-secret
            key: PMA_USER
      - name: PMA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: phpadmin-secret
            key: PMA_PASSWORD
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: phpadmin-nodeport-svc
spec:
  type: NodePort
  selector:
    run: phpadmin-pod
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
      nodePort: 31000  # Choose a node port within the range 30000-32767

