apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpadmin
  template:
    metadata:
      labels:
        app: phpadmin
    spec:
      containers:
        - name: phpadmin-container
          image: phpmyadmin
          env:
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: phpadmin-config
                  key: PMA_HOST
            - name: PMA_PORT
              valueFrom:
                configMapKeyRef:
                  name: phpadmin-config
                  key: PMA_PORT
            - name: PMA_USER
              valueFrom:
                secretKeyRef:
                  name: phpadmin-secret
                  key: PMA_USER
            - name: PMA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phpadmin-secret
                  key: PMA_PASSWORD
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: phpadmin-nodeport-svc
spec:
  type: NodePort
  selector:
    app: phpadmin
  ports:
    - protocol: TCP
      port: 8099
      targetPort: 80
      nodePort: 31111  # Choose a node port within the range 30000-32767
